# Project information
site_name: Workshop Setup
site_url: https://remkohdev.github.io/workshop-setup
site_author: IBM Developer

# Repository
repo_name: workshop-setup
repo_url: https://github.com/remkohdev/workshop-setup
edit_uri: edit/master/docs

# Navigation
nav:
  - Welcome:
    - About the workshop: README.md

  - Docs:
    - Calico: CALICO.md
    - IBM Cloud Shell: CLOUDSHELL.md
    - Labs at CognitiveClass.ai: COGNITIVECLASS.md
    - Free Kubernetes Cluster: FREEIKSCLUSTER.md
    - Grant Cluster Permissions: GRANTCLUSTER.md
    - Helm v3: HELM.md
    - Jenkins: JENKINS.md
    - MkDocs: MKDOCS.md
    - New IBM Cloud: NEWACCOUNT.md
    - Source-to-Image (S2I): S2I.md
    - Upgrade IBM Cloud account to Pay-As-You-Go: PAYASYOUGO.md
    - Connect to RedHat OpenShift Kubernetes Service (ROKS): ROKS.md
    - Free OpenShift Cluster: OPENLABS.md

  - References:
    - Additional Resources: references/RESOURCES.md
    - Contributors: references/CONTRIBUTORS.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2020 IBM Developer

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: ibm_8bar_reverse_2
  features:
    - navigation.tabs
    #- navigation.instant
    - navigation.expand
  palette:
    scheme: default
    primary: black
    accent: blue
  custom_dir: overrides

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/developerworks
    - icon: fontawesome/brands/dev
      link: https://dev.to/ibmdeveloper

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde